--CREATE TABLE "ProductResults" (
--	"Id"	INTEGER NOT NULL,
--	"ProductId"	TEXT,
--	"ProductName"	TEXT,
--	"ProductType"	TEXT,
--	"AdjustmentType"	TEXT,
--	"Quantity"	TEXT,
--	"SelectedUnit"	TEXT,
--	"CreateTimestamp"	TEXT,
--	"UpdateTimestamp"	TEXT,
--	"CompletedCount"	INTEGER NOT NULL DEFAULT 0,
--	CONSTRAINT "PK_ProductResults" PRIMARY KEY("Id" AUTOINCREMENT)
--);